# -----------------------------------------------------------------------------
#
# A license is hereby granted to reproduce this software source code and
# to create executable versions from this source code for personal,
# non-commercial use.  The copyright notice included with the software
# must be maintained in all copies produced.
#
# THIS PROGRAM IS PROVIDED "AS IS". THE AUTHOR PROVIDES NO WARRANTIES
# WHATSOEVER, EXPRESSED OR IMPLIED, INCLUDING WARRANTIES OF
# MERCHANTABILITY, TITLE, OR FITNESS FOR ANY PARTICULAR PURPOSE.  THE
# AUTHOR DOES NOT WARRANT THAT USE OF THIS PROGRAM DOES NOT INFRINGE THE
# INTELLECTUAL PROPERTY RIGHTS OF ANY THIRD PARTY IN ANY COUNTRY.
#
# Copyright (c) 1994-2006, John Conover, All Rights Reserved.
#
# Comments and/or bug reports should be addressed to:
#
#     john@email.johncon.com (John Conover)
#
# -----------------------------------------------------------------------------
#
# Makefile for the markets.
#
# $Revision: 0.0 $
# $Date: 2006/01/15 03:05:12 $
# $Id: Makefile,v 0.0 2006/01/15 03:05:12 john Exp $
# $Log: Makefile,v $
# Revision 0.0	2006/01/15 03:05:12  john
# Initial version
#
#
all:
	(cd computer.office;make;cd ../)
	(cd dj;make;cd ../)
	(cd crus;make;cd ../)
	(cd electronic.components.production;make;cd ../)
	(cd electronic.components.shipments;make;cd ../)
	(cd electronics;make;cd ../)
	(cd ic.namerica;make;cd ../)
	(cd information.systems;make;cd ../)
	(cd semiconductors.namerica;make;cd ../)
	(cd semiconductors.world;make;cd ../)
	(cd tscoin;make;cd ../)
	(cd tscoin.tsunfairbrownian;make;cd ../)
	(cd tscoin.tsunfairbrownian.tssample;make;cd ../)
	(cd tscoin.tssample;make;cd ../)
	(cd tsunfairbrownian.exponential;make;cd ../)
	(cd us.employment;make;cd ../)
	(cd us.gdp;make;cd ../)
	(cd us.indicators;make;cd ../)
	(cd us.m2;make;cd ../)
	(cd us.tbill;make;cd ../)
	(cd tscoins;make;cd ../)
	(cd tsmarket;make;cd ../)
	(cd tscoins-f;make;cd ../)
	(cd tsdlogistic;make;cd ../)
	(cd tsgaussian.tsmath.tsmath.tsunfraction;make;cd ../)
	(cd tscoins-b;make;cd ../)
clean:
	(cd computer.office;make clean;cd ../)
	(cd dj;make clean;cd ../)
	(cd crus;make clean;cd ../)
	(cd electronic.components.production;make clean;cd ../)
	(cd electronic.components.shipments;make clean;cd ../)
	(cd electronics;make clean;cd ../)
	(cd ic.namerica;make clean;cd ../)
	(cd information.systems;make clean;cd ../)
	(cd semiconductors.namerica;make clean;cd ../)
	(cd semiconductors.world;make clean;cd ../)
	(cd tscoin;make clean;cd ../)
	(cd tscoin.tsunfairbrownian;make clean;cd ../)
	(cd tscoin.tsunfairbrownian.tssample;make clean;cd ../)
	(cd tscoin.tssample;make clean;cd ../)
	(cd tsunfairbrownian.exponential;make clean;cd ../)
	(cd us.employment;make clean;cd ../)
	(cd us.gdp;make clean;cd ../)
	(cd us.indicators;make clean;cd ../)
	(cd us.m2;make clean;cd ../)
	(cd us.tbill;make clean;cd ../)
	(cd tscoins;make clean;cd ../)
	(cd tsmarket;make clean;cd ../)
	(cd tscoins-f;make clean;cd ../)
	(cd tsdlogistic;make clean;cd ../)
	(cd tsgaussian.tsmath.tsmath.tsunfraction;make clean;cd ../)
	(cd tscoins-b;make clean;cd ../)
realclean:
	(cd computer.office;make realclean;cd ../)
	(cd dj;make realclean;cd ../)
	(cd crus;make realclean;cd ../)
	(cd electronic.components.production;make realclean;cd ../)
	(cd electronic.components.shipments;make realclean;cd ../)
	(cd electronics;make realclean;cd ../)
	(cd ic.namerica;make realclean;cd ../)
	(cd information.systems;make realclean;cd ../)
	(cd semiconductors.namerica;make realclean;cd ../)
	(cd semiconductors.world;make realclean;cd ../)
	(cd tscoin;make realclean;cd ../)
	(cd tscoin.tsunfairbrownian;make realclean;cd ../)
	(cd tscoin.tsunfairbrownian.tssample;make realclean;cd ../)
	(cd tscoin.tssample;make realclean;cd ../)
	(cd tsunfairbrownian.exponential;make realclean;cd ../)
	(cd us.employment;make realclean;cd ../)
	(cd us.gdp;make realclean;cd ../)
	(cd us.indicators;make realclean;cd ../)
	(cd us.m2;make realclean;cd ../)
	(cd us.tbill;make realclean;cd ../)
	(cd tscoins;make realclean;cd ../)
	(cd tsmarket;make realclean;cd ../)
	(cd tscoins-f;make realclean;cd ../)
	(cd tsdlogistic;make realclean;cd ../)
	(cd tsgaussian.tsmath.tsmath.tsunfraction;make realclean;cd ../)
	(cd tscoins-b;make realclean;cd ../)
