-- v1.1: Pre-populate Canadian brokerages
INSERT IGNORE INTO brokerages (name) VALUES
('RBC Direct Investing'),
('TD Direct Investing'),
('Scotia iTRADE'),
('BMO InvestorLine'),
('CIBC Investor’s Edge'),
('National Bank Direct Brokerage'),
('Desjardins Online Brokerage'),
('Questrade'),
('Qtrade'),
('Wealthsimple Trade'),
('Virtual Brokers'),
('HSBC InvestDirect'),
('Credential Direct'),
('Interactive Brokers Canada'),
('Laurentian Bank Discount Brokerage'),
('Manulife Securities'),
('Canaccord Genuity'),
('Richardson Wealth'),
('PI Financial'),
('Raymond James'),
('Industrial Alliance Securities'),
('Mackie Research Capital'),
('Leede Jones Gable'),
('BBS Securities'),
('Friedberg Direct'),
('B2B Bank Dealer Services'),
('Vanguard Canada'),
('Invesco Canada'),
('Fidelity Investments Canada'),
('Edward Jones Canada'),
('Other');
