-- v1.1: Pre-populate Canadian account types
INSERT IGNORE INTO account_types (name) VALUES
('Cash'),
('Margin'),
('TFSA'),
('RRSP'),
('RRIF'),
('RESP'),
('LIRA'),
('LIF'),
('Corporate'),
('Joint'),
('Trust'),
('USD Cash'),
('USD Margin'),
('USD TFSA'),
('USD RRSP'),
('USD RRIF'),
('USD RESP'),
('USD LIRA'),
('USD LIF'),
('USD Corporate'),
('USD Joint'),
('USD Trust'),
('Other');
