# Kubernetes Pod Configuration for Stock Analysis Application
# This creates a single pod with multiple containers for simplified deployment
# For production, consider using separate Deployments and Services

apiVersion: v1
kind: Pod
metadata:
  name: stock-analysis
  labels:
    app: stock-analysis
    tier: application
spec:
  containers:
  # MySQL Database Container
  - name: mysql
    image: mysql:8.0
    ports:
    - containerPort: 3306
      name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: stock-analysis-secrets
          key: mysql-root-password
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: stock-analysis-config
          key: mysql-database
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: stock-analysis-config
          key: mysql-user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: stock-analysis-secrets
          key: mysql-password
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
    - name: mysql-init
      mountPath: /docker-entrypoint-initdb.d
      readOnly: true
    livenessProbe:
      exec:
        command:
        - mysqladmin
        - ping
        - -h
        - localhost
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    resources:
      limits:
        memory: "1Gi"
        cpu: "500m"
      requests:
        memory: "512Mi"
        cpu: "250m"

  # Redis Cache Container
  - name: redis
    image: redis:7-alpine
    command:
    - redis-server
    - --requirepass
    - $(REDIS_PASSWORD)
    - --maxmemory
    - 256mb
    - --maxmemory-policy
    - allkeys-lru
    ports:
    - containerPort: 6379
      name: redis
    env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: stock-analysis-secrets
          key: redis-password
    volumeMounts:
    - name: redis-data
      mountPath: /data
    livenessProbe:
      exec:
        command:
        - redis-cli
        - --raw
        - incr
        - ping
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    resources:
      limits:
        memory: "512Mi"
        cpu: "250m"
      requests:
        memory: "256Mi"
        cpu: "100m"

  # Application Container
  - name: app
    image: stock-analysis:latest
    ports:
    - containerPort: 80
      name: http
    env:
    # Database Configuration
    - name: DB_HOST
      value: "localhost"  # Same pod, so localhost
    - name: DB_PORT
      value: "3306"
    - name: DB_DATABASE
      valueFrom:
        configMapKeyRef:
          name: stock-analysis-config
          key: mysql-database
    - name: DB_USERNAME
      valueFrom:
        configMapKeyRef:
          name: stock-analysis-config
          key: mysql-user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: stock-analysis-secrets
          key: mysql-password
    
    # Redis Configuration
    - name: REDIS_HOST
      value: "localhost"  # Same pod, so localhost
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: stock-analysis-secrets
          key: redis-password
    - name: REDIS_DATABASE
      value: "0"
    
    # Application Configuration
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: stock-analysis-config
          key: app-name
    - name: APP_ENV
      value: "production"
    - name: APP_DEBUG
      value: "false"
    - name: APP_ROOT
      value: "/var/www/stock-analysis"
    - name: APP_DOMAIN
      valueFrom:
        configMapKeyRef:
          name: stock-analysis-config
          key: app-domain
    
    # Python Configuration
    - name: PYTHON_PATH
      value: "/var/www/stock-analysis/venv/bin/python"
    
    # Migrations
    - name: RUN_MIGRATIONS
      value: "true"
    
    volumeMounts:
    - name: app-data
      mountPath: /var/www/stock-analysis/data
    - name: app-logs
      mountPath: /var/www/stock-analysis/logs
    - name: app-uploads
      mountPath: /var/www/stock-analysis/uploads
    
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests:
        memory: "1Gi"
        cpu: "500m"

  # Shared volumes within the pod
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: stock-analysis-mysql-pvc
  - name: mysql-init
    configMap:
      name: stock-analysis-mysql-init
  - name: redis-data
    persistentVolumeClaim:
      claimName: stock-analysis-redis-pvc
  - name: app-data
    persistentVolumeClaim:
      claimName: stock-analysis-app-data-pvc
  - name: app-logs
    persistentVolumeClaim:
      claimName: stock-analysis-app-logs-pvc
  - name: app-uploads
    persistentVolumeClaim:
      claimName: stock-analysis-app-uploads-pvc

  restartPolicy: Always

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-analysis-config
data:
  app-name: "stock-analysis"
  app-domain: "example.com"
  mysql-database: "stock_analysis"
  mysql-user: "stock_app"

---
# Secret for sensitive data (base64 encoded)
# To create: kubectl create secret generic stock-analysis-secrets \
#   --from-literal=mysql-root-password=changeme \
#   --from-literal=mysql-password=changeme \
#   --from-literal=redis-password=changeme
apiVersion: v1
kind: Secret
metadata:
  name: stock-analysis-secrets
type: Opaque
data:
  # Default values (base64 encoded "changeme")
  # Replace these with actual values: echo -n "yourpassword" | base64
  mysql-root-password: Y2hhbmdlbWU=
  mysql-password: Y2hhbmdlbWU=
  redis-password: Y2hhbmdlbWU=

---
# PersistentVolumeClaim for MySQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-analysis-mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Adjust based on your cluster

---
# PersistentVolumeClaim for Redis data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-analysis-redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

---
# PersistentVolumeClaim for Application data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-analysis-app-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
# PersistentVolumeClaim for Application logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-analysis-app-logs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

---
# PersistentVolumeClaim for Application uploads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-analysis-app-uploads-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
# Service to expose the pod
apiVersion: v1
kind: Service
metadata:
  name: stock-analysis-service
  labels:
    app: stock-analysis
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP as needed
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: stock-analysis
    tier: application
