@startuml
class DatabaseRepository {
    +getSymbolTechnicalTableName(symbol: string): string
    +createSymbolTechnicalTable(symbol: string): bool
    +saveSymbolTechnicalValues(symbol: string, values: array): bool
}
@enduml
